//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estrol.X3Solo.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estrol.X3Solo.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EMUCONFIG]\r\nVersion             = 1.0\r\nServerPort          = 15010\r\n\r\n[CHARACTER]\r\nName                = X3Solo\r\nLevel               = 100\r\nRank                = 1\r\nGender              = 0\r\nInstrument          = 0\r\nHair                = 0\r\nAccessory           = 0\r\nGlove               = 0\r\nNecklace            = 0\r\nTop                 = 0\r\nPant                = 0\r\nGlass               = 0\r\nEarring             = 0\r\nShoe                = 0\r\nFace                = 36\r\nWing  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DEFAULTCONF {
            get {
                return ResourceManager.GetString("DEFAULTCONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EMUCONFIG]
        ///Version             = 1.0
        ///ServerPort          = 15010
        ///
        ///[CHARACTER]
        ///Name                = X3Solo
        ///Level               = 100
        ///Rank                = 1
        ///Gender              = 0
        ///Instrument          = 0
        ///Hair                = 0
        ///Accessory           = 0
        ///Glove               = 0
        ///Necklace            = 0
        ///Top                 = 0
        ///Pant                = 0
        ///Glass               = 0
        ///Earring             = 0
        ///Shoe                = 0
        ///Face                = 36
        ///Wing                = 0
        ///HairAccessory        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string solo {
            get {
                return ResourceManager.GetString("solo", resourceCulture);
            }
        }
    }
}
